# CREATE DATABASE MYC_DB; #创建数据库
# DROP DATABASE MYC_DB; #删除数据库
SHOW DATABASES;

USE MYC_DB; # 使用数据库

-- CREATE TABLE TBL_USER ( # 创建User表格
-- U_ID INT PRIMARY KEY AUTO_INCREMENT,
-- U_NAME VARCHAR(32),
-- U_GENGDER VARCHAR(8)
-- );

SHOW TABLES; # 显示table

SELECT * FROM TBL_USER;

INSERT TBL_USER(U_NAME, U_GENGDER) VALUES('Mayc', 'man');

# DELETE FROM TBL_USER WHERE U_NAME='Mayc'; # 提醒不安全，因为可能会同时有多条数据被删除


-- SET SQL_SAFE_UPDATES=0; # 设置成安全模式, 三条语句同时做
-- DELETE FROM TBL_USER WHERE U_NAME='Mayc';
-- SET SQL_SAFE_UPDATES=1;
sql -->
# 更好的方式

DELIMITER $$
CREATE PROCEDURE PROC_DELETE_USER(IN UNAME VARCHAR(32))
BEGIN
SET SQL_SAFE_UPDATES=0; # 设置成安全模式, 三条语句同时做
DELETE FROM TBL_USER WHERE U_NAME=UNAME;
SET SQL_SAFE_UPDATES=1;
END$$

CALL PROC_DELETE_USER('qiuxiang')



