# CREATE DATABASE MYC_DB; #创建数据库
# DROP DATABASE MYC_DB; #删除数据库
SHOW DATABASES;

USE MYC_DB; # 使用数据库

-- CREATE TABLE TBL_USER ( # 创建User表格
-- U_ID INT PRIMARY KEY AUTO_INCREMENT,
-- U_NAME VARCHAR(32),
-- U_GENGDER VARCHAR(8)
-- );

SHOW TABLES; # 显示table

SELECT * FROM TBL_USER;

INSERT TBL_USER(U_NAME, U_GENGDER) VALUES('Mayc', 'man');